_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.0
            "5": 0.19.8
            "6": 4.50.2
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
